---
title: "wrangling the data"
author: "Kristin Gill"
date: "1/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(rgdal)
```

Sea Otter Strandings
```{r}
sea_otter_data <- read_csv(here("data", "Table2_StrandedSeaOtter_byLifeStage_1985_2017.csv")) %>% 
  clean_names() %>% 
  pivot_longer(cols = 3:20, names_to = "life_stage", values_to = "count") %>% 
  select(!total) %>% 
  mutate(life_stage = case_when(
    life_stage == "pups_f" ~ "pups:female",
    life_stage == "juvenile_f" ~ "juvenile:female",
    life_stage == "sub_adult_f" ~ "subadult:female",
    life_stage == "adult_f" ~ "adult:female",
    life_stage == "old_adult_f" ~ "old_adult:female",
    life_stage == "unknown_f" ~ "unknown:female",
    life_stage == "pups_m" ~ "pups:male",
    life_stage == "juvenile_m" ~ "juvenile:male",
    life_stage == "sub_adult_m" ~ "subadult:male",
    life_stage == "adult_m" ~ "adult:male",
    life_stage == "old_adult_m" ~ "old_adult:male",
    life_stage == "unknown_m" ~ "unknown:male",
    life_stage == "pups_u" ~ "pups:unknown",
    life_stage == "juvenile_u" ~ "juvenile:unknown",
    life_stage == "sub_adult_u" ~ "subadult:unknown",
    life_stage == "adult_u" ~ "adult:unknown",
    life_stage == "old_adult_u" ~ "old_adult:unknown",
    life_stage == "unknown_u" ~ "unknown:unknown"
  )) %>% 
  separate(life_stage, c("life_stage", "sex"))

ggplot(data = sea_otter_data, aes(x = year,
                                  y = count)) +
      geom_col(aes(fill = life_stage))
```

Sea Otter Annual Census
```{r}
census_sea_otter <- read_csv(here("data", "AnnualCaliforniaSeaOtter_Census_summary_1985_2014.csv")) %>% 
  clean_names()
```

Stranded Sea Otter by Geographic Location
```{r}
geog_sea_otter <- read_csv(here("data", "Table1_StrandedSeaOtter_byGeographicAreas_1985_2017.csv")) %>% 
  clean_names() %>% 
  select(!total_strandings) %>% 
  pivot_longer(cols = 2:15, names_to = "location", values_to = "count")
```

Stranded Sea Otter by Year and Month
```{r}
pop_sea_otter <- read_csv(here("data", "Table3_StrandedSeaOtter_byYearAndMonth_1985_2017.csv")) %>% 
  clean_names() %>% 
  select(!total) %>% 
  pivot_longer(cols = 3:14, names_to = "month", values_to = "count")
```

Sea otter locations
```{r}
locations_sea_otters <- readOGR(
  dsn = "~/data/shapefile_2019/Census_sum_2019",
  layer = "Census_sum_2019")
```

